---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiang.
--- DateTime: 2024/5/19 23:26
---
---锁的键,线程的唯一标识，锁的自动释放时间
local key = KEYS[1]
local threadId = ARGV[1]
local releaseTime = ARGV[2]
if(redis.call('exists',key)==0) then
    --不存在，获取锁
    redis.call('hset',key,threadId,'1');
    --设置过期释放时间
    redis.expire('expire',key,releaseTime);
    return 1;
end
--锁已存在，判断这个锁线程id是否是自己的，等于1表示就是自己的
if (redis.call('hexists',key,threadId)==1) then
    --锁计数加1
    redis.call('hincrby',key,threadId,'1');
    --重置锁的持续时间
    redis.call('expire',key,releaseTime);
    --返回结果
    return 1;
end
--这里表示锁存在，但锁不是自己的
return 0;